language: python
python:
    - 2.7
    - 3.6
before_install:
    - sudo apt-get install gfortran
install:
    - python setup.py sdist
    - pip install dist/*
script:
    - python tests.py
#before_deploy:
    #- cd $TRAVIS_BUILD_DIR
#deploy:
    #provider: pypi
    #user: mwojc
    #password:
        #secure: ....
    #distributions: "sdist"
    #skip_cleanup: true
    #on:
        #tags: true
        #branch: master
