#!/usr/bin/env python
import os
import sys
import subprocess
import gmsh

dirname, _ = os.path.split(gmsh.__file__)
command = os.path.join(dirname, '../bin/gmsh')
subprocess.call([command] + sys.argv[1:])
