#!/usr/bin/env python
import os
import sys
import subprocess
import gmsh

dirname, _ = os.path.split(gmsh.__file__)
os.putenv('LD_LIBRARY_PATH', dirname)
os.putenv('PATH', dirname)
command = os.path.join(dirname, '../bin/gmsh')
subprocess.call([command] + sys.argv[1:])

